version: '3.9'

services:

  frontend:
    container_name: "pik_front"
    build: ./front
    ports:
      - '8001:5173'
    volumes:
      - ../:/app
    command: sh -c "yarn install && yarn dev --host 0.0.0.0"
